# Generated by Django 2.1.2 on 2018-11-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=5)),
                ('e_mail', models.CharField(max_length=20)),
            ],
        ),
    ]
